try
{
  console.log('started practicing program');
  feelingsleepy;
  console.log('end of practicing program');
}
catch(error)
{
    console.log('error has accured:'+ error.message);
}
finally
{
    console.log('Because of fear again started doing programs');
}
console.log('finnaly done with program hurray');